name: Diagnosticar SSH

on:
  workflow_dispatch:

jobs:
  test-ssh:
    runs-on: ubuntu-latest
    steps:
      - name: Probar conexión SSH
        run: |
          ssh -v -o ConnectTimeout=10 -o StrictHostKeyChecking=no ec2-user@98.81.228.251
