name: Build, Push & Deploy frontend
on:
  push:
    branches: [ deploy ]
  workflow_dispatch:

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configurar credenciales AWS
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login a ECR
        id: ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build y Push imagen
        run: |
          IMAGE=${{ steps.ecr.outputs.registry }}/casino-frontend
          docker build -t $IMAGE:${{ github.sha }} -t $IMAGE:latest .
          docker push $IMAGE:${{ github.sha }}
          docker push $IMAGE:latest

  deploy:
    runs-on: self-hosted
    needs: build-push
    steps:
      - name: Deploy en EC2 frontend
        run: |
          aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
            | docker login --username AWS --password-stdin \
              ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

          ssh -o StrictHostKeyChecking=no \
              -i ~/.ssh/gh-actions-key \
              ec2-user@172.31.19.136 \
            "aws ecr get-login-password --region ${{ secrets.AWS_REGION }} \
              | docker login --username AWS --password-stdin \
                ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com && \
             docker pull ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/casino-frontend:latest && \
             docker rm -f casino-frontend || true && \
             docker run -d --name casino-frontend --restart unless-stopped \
               -p 80:8080 \
               -e BACKEND_HOST=172.31.16.201 \
               ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/casino-frontend:latest"
