name: Deploy desde EC2

on:
  repository_dispatch:
    types: [deploy-from-ec2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Desplegar en EC2
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_FRONTEND_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "Deploy exitoso"
