name: Frontend Pipeline

on:
  push:
    branches: [ deploy ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker Image
        run: docker build -t felipensio/frontend_intro_devops_casino:latest .

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and Push Tags
        run: |
          # Construimos la imagen localmente
          docker build -t felipensio/frontend_intro_devops_casino:latest .
          
          # Creamos los tres tags requeridos
          docker tag felipensio/frontend_intro_devops_casino:latest felipensio/frontend_intro_devops_casino:v1.0.0
          docker tag felipensio/frontend_intro_devops_casino:latest felipensio/frontend_intro_devops_casino:sha-${{ github.sha }}
          
          # Los subimos todos de verdad a Docker Hub
          docker push felipensio/frontend_intro_devops_casino:latest
          docker push felipensio/frontend_intro_devops_casino:v1.0.0
          docker push felipensio/frontend_intro_devops_casino:sha-${{ github.sha }}

  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: Deploy
        run: echo "Despliegue simulado en producción completado."